# Publishing pipeline
# ref: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: Publish Python distribution 📦 to PyPI

on:
  push:
    branches:
      - 'main'
      - 'releases/**'
      - 'develop'
      # Test
      - 'feature/ppl-bump_on_pr*'

env:
  publishPackage: false

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: debug
      run: echo github.ref, echo github.event_name

    - name: Bump version
      if: github.event_name == 'pull_request' && github.ref == 'refs/heads/feature/ppl-bump_on_pr'
      run: |
        poetry version patch

        git config --local user.email "gian.angelini@hotmail.com"
        git config --local user.name "gianfa"
        git add pyproject.toml poetry.lock
        git commit -m "bump to v$(poetry version --short)"
        git push
  
    - name: Publish Package
      if: env.publishPackage == 'true'
      uses: celsiusnarhwal/poetry-publish@v2
      with:
        python-version: 3.9
        poetry-version: 1.7.0
        token: ${{ secrets.PYPI_TOKEN }}
        build: true